### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by weotch** [BKWLD/nuxt-remote-asset-cache#1]
- [x] Pass in all settings form nuxt options
  - [x] Don't run if no cache dir
- [x] Copy assets directory into public directory
  - [x] Maybe I store in cache in a namespaced directory... 
- [x] Write docs
